name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_ADMIN_UID: ${{ secrets.VITE_ADMIN_UID }}
      VITE_ADMIN_GH_USERNAME: ${{ secrets.VITE_ADMIN_GH_USERNAME }}
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install            # use npm ci only if lockfile is committed
      - run: npm run build

      - name: SPA fallback (copy index -> 404)
        run: cp dist/index.html dist/404.html

      - name: Create .env.production
        run: |
          echo "VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}" >> .env.production
          echo "VITE_ADMIN_UID=${VITE_ADMIN_UID}" >> .env.production
          echo "VITE_ADMIN_GH_USERNAME=${VITE_ADMIN_GH_USERNAME}" >> .env.production
          echo "Wrote env file"

      - name: Debug env presence (length only)
        run: |
          echo "API key length: ${#VITE_FIREBASE_API_KEY}"
          echo "Admin UID length: ${#VITE_ADMIN_UID}"
          echo "Admin GH length: ${#VITE_ADMIN_GH_USERNAME}"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4